---
title: "Hong Kong Horse Racing Predictions"
author: "Derek Kruszewski, Yi Liu, Rob Blumberg, Carlina Kim </br>"
date: "2020/01/24 (updated: `r Sys.Date()`)"
output:
  github_document:
    toc: true
bibliography: final_report.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = here::here())
```

## Introduction

Hong Kong horse racing bets contributed a staggering $15.8 billion USD turnover for 2017-2018 [@ng]. With such large amounts of money being wagered, it **spurs** the question: "Given a set of features related to racing horses, can we predict the outcome of a race?".

A publically available dataset with Hong Kong horse racing statistics is available on Kaggle [@Dataset] for 2015-2017. The data set author mentions that this data was compiled from data from The Hong Kong Jockey Club [@HKJC]. This data was utilized to create a predictive model for horse performance. The following report sections explore this data and comment on the success of said model.

The R and Python programming languages were used in this analysis [@R; @Python]. Python packages used in the analysis include: pandas [@mckinney-proc-scipy-2010], docopt [@docoptpython], numpy [@numpy], scikit-learn [@scikit-learn], altair [@Altair2018], pandas profiling [@pandasprofiling2019], matplotlib [@Hunter:2007], and seaborn (citation still under development). R packages used in this analysis include: knitr [@knitr], docopt [@docopt], and tidyverse [@tidyverse].

## Exploratory Data Analysis

- Introduce data set

## Analysis

- Present results in context of question
- Critique of analysis
  - limitations
  - assumptions
  - future directions

## References
